# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: scenescape-chart
description: A Helm chart for SceneScape
type: application
version: 1.2.1
appVersion: "1.4.0-rc1"
