---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Publish Docs

on:
  workflow_dispatch:

permissions:
  contents: read # needed for actions/checkout
  pull-requests: read # needed for gh pr list
  issues: write # needed to post PR comment

jobs:
  build_toplevel:
    uses: open-edge-platform/orch-ci/.github/workflows/publish-documentation.yml@628dd6e7fd94a3e765e389b5bb43d90fbe3de421
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}

  build_autocalibration:
    needs: build_toplevel
    uses: open-edge-platform/orch-ci/.github/workflows/publish-documentation.yml@628dd6e7fd94a3e765e389b5bb43d90fbe3de421
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: autocalibration

  build_controller:
    needs: build_toplevel
    uses: open-edge-platform/orch-ci/.github/workflows/publish-documentation.yml@628dd6e7fd94a3e765e389b5bb43d90fbe3de421
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: controller

  build_percebro:
    needs: build_toplevel
    uses: open-edge-platform/orch-ci/.github/workflows/publish-documentation.yml@628dd6e7fd94a3e765e389b5bb43d90fbe3de421
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: percebro
